---
name: Check 🛠

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
    branches:
      - main
  push:
    branches:
      - main
      - codespaces_conf

# This reusable workflow from insightsengineering/r.pkg.template will run once a PR to main branch is created.
jobs:
  job-setup:
    name: Should we run R CMD check?
    runs-on: ubuntu-latest
    outputs:
      check_out: ${{ steps.check.outputs.run_r_cmd_check }}
    steps:
      - name: To check or not to check?
        id: check
        run: |
          echo "run_r_cmd_check=false" >> $GITHUB_OUTPUT

  r-cmd:
    name: R CMD Check 🧬
    needs: job-setup
    # Call a workflow from a given GitHub repository, from a given branch (or tag).
    uses: insightsengineering/r.pkg.template/.github/workflows/build-check-install.yaml@main
    if: >
      needs.job-setup.outputs.check_out == 'true'

  job-setup-with-docker:
    name: Let's run R CMD check using containers
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/user-workshop-cicd/r-pkg-example:4.3"

    steps:
      # note : we can not use reusable workflow build-check-install.yaml@main within container context (only actions)
      - name: Checkout repo
        uses: actions/checkout@v4.1.1
        with:
          path: ${{ github.event.repository.name }}

      - name: Running R CMD Check using r-pkg-example:4.3 image
        run: |
          echo "ls"
          ls
          echo "ls workspace"
          ls /workspace
          echo $$GITHUB_WORKSPACE
          ls $GITHUB_WORKSPACE
          ls "$GITHUB_WORKSPACE/r.package.example"

      - name: Running R CMD Check using r-pkg-example:4.3 image
        run: |
          R CMD check "$GITHUB_WORKSPACE/r.package.example"
